POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Vammasen Ympärilläni",
    "author": "Niina Mattola",
    "url": "https://codesamson.com",
    "likes": "99",
    "userId": "5eca5c6cca3216319ca6bce9"
}